// Generated by gencpp from file holonomic_robot/ManualCommands.msg
// DO NOT EDIT!


#ifndef HOLONOMIC_ROBOT_MESSAGE_MANUALCOMMANDS_H
#define HOLONOMIC_ROBOT_MESSAGE_MANUALCOMMANDS_H

#include <ros/service_traits.h>


#include <holonomic_robot/ManualCommandsRequest.h>
#include <holonomic_robot/ManualCommandsResponse.h>


namespace holonomic_robot
{

struct ManualCommands
{

typedef ManualCommandsRequest Request;
typedef ManualCommandsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManualCommands
} // namespace holonomic_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::holonomic_robot::ManualCommands > {
  static const char* value()
  {
    return "bd763a4aa4ede563f73c7d9469f42e99";
  }

  static const char* value(const ::holonomic_robot::ManualCommands&) { return value(); }
};

template<>
struct DataType< ::holonomic_robot::ManualCommands > {
  static const char* value()
  {
    return "holonomic_robot/ManualCommands";
  }

  static const char* value(const ::holonomic_robot::ManualCommands&) { return value(); }
};


// service_traits::MD5Sum< ::holonomic_robot::ManualCommandsRequest> should match
// service_traits::MD5Sum< ::holonomic_robot::ManualCommands >
template<>
struct MD5Sum< ::holonomic_robot::ManualCommandsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::holonomic_robot::ManualCommands >::value();
  }
  static const char* value(const ::holonomic_robot::ManualCommandsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::holonomic_robot::ManualCommandsRequest> should match
// service_traits::DataType< ::holonomic_robot::ManualCommands >
template<>
struct DataType< ::holonomic_robot::ManualCommandsRequest>
{
  static const char* value()
  {
    return DataType< ::holonomic_robot::ManualCommands >::value();
  }
  static const char* value(const ::holonomic_robot::ManualCommandsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::holonomic_robot::ManualCommandsResponse> should match
// service_traits::MD5Sum< ::holonomic_robot::ManualCommands >
template<>
struct MD5Sum< ::holonomic_robot::ManualCommandsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::holonomic_robot::ManualCommands >::value();
  }
  static const char* value(const ::holonomic_robot::ManualCommandsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::holonomic_robot::ManualCommandsResponse> should match
// service_traits::DataType< ::holonomic_robot::ManualCommands >
template<>
struct DataType< ::holonomic_robot::ManualCommandsResponse>
{
  static const char* value()
  {
    return DataType< ::holonomic_robot::ManualCommands >::value();
  }
  static const char* value(const ::holonomic_robot::ManualCommandsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOLONOMIC_ROBOT_MESSAGE_MANUALCOMMANDS_H
