// Generated by gencpp from file robot_tutorial/ManualCommandsResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_TUTORIAL_MESSAGE_MANUALCOMMANDSRESPONSE_H
#define ROBOT_TUTORIAL_MESSAGE_MANUALCOMMANDSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_tutorial
{
template <class ContainerAllocator>
struct ManualCommandsResponse_
{
  typedef ManualCommandsResponse_<ContainerAllocator> Type;

  ManualCommandsResponse_()
    : response()  {
    }
  ManualCommandsResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ManualCommandsResponse_

typedef ::robot_tutorial::ManualCommandsResponse_<std::allocator<void> > ManualCommandsResponse;

typedef boost::shared_ptr< ::robot_tutorial::ManualCommandsResponse > ManualCommandsResponsePtr;
typedef boost::shared_ptr< ::robot_tutorial::ManualCommandsResponse const> ManualCommandsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator1> & lhs, const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator1> & lhs, const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_tutorial/ManualCommandsResponse";
  }

  static const char* value(const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
;
  }

  static const char* value(const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManualCommandsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_tutorial::ManualCommandsResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TUTORIAL_MESSAGE_MANUALCOMMANDSRESPONSE_H
